### ISSUE TITLE
add support for compiler participants ?

### ISSUE THREAD

**Issue by foreveremain** [TheMrMilchmann/gradle-ecj#1]
Thanks so much for creating this new ecj plugin !  Do you think there's a possibility to allow execution of ecj compiler participants ?   These are normally bundled as regular eclipse plugins, and the one I'm familiar with is https://github.com/java2script/java2script/ - which transpiles Java code to .js files, allowing Java swing apps to run in the browser (I develop this one: https://www.jalview.org/jalview-js/JalviewJS.shtml but the plugin's main developer is @BobHanson, who also develops https://chemapps.stolaf.edu/jmol/jsmol/jsmol.htm ).

**Comment by TheMrMilchmann** [comment]
Hi! I've taken a brief look at Eclipse JDT's compilation participants but I'm not sure what is required to set them up. This plugin is invoking ECJ via its command line interface and all I can find are docs about how to set it up programmatically. This is something I am not willing to change since a programmatic solution would require using a lot of unstable Gradle internals.

Also note that if it's possible to add participants via CLI, you should already be able to do that by modifying the `freeCompilerArgs` of the `JavaCompile` task. It is possible that I'm misunderstanding something, so if you have more information, please let me know.

**Comment by TheMrMilchmann** [comment]
Due to the lack of follow-up and the reasons stated above, this will not be worked on for now. I might revisit this at some point if Gradle opens up the API for custom Java compilers.

**Comment by foreveremain** [comment]
Nice to see some activity here. The news that gradle 8 might not support ecj meant I didn't pursue this further - and somehow I missed your july 21 comment about freeCompilerArgs. We're still working with the java2script compiler participant - perhaps I'll find some time to experiment.
