### ISSUE TITLE
Is it possible to increase the ecj's jvm memory limit?

### ISSUE THREAD

**Issue by liufuyang** [TheMrMilchmann/gradle-ecj#23]
Hey there, thanks for creating this plugin.

Is there a way to increase the java memory limit when loading ecj? Thanks.

**Comment by liufuyang** [comment]
Hmmm, looks like I can just keep using the `JavaCompile` task and add some jvmArgs on forkOptions.

```kts
tasks.withType<JavaCompile> {
    options.forkOptions.jvmArgs =  listOf("-Xms2048m", "-Xmx4096m")
}
```

It seems worked.

**Comment by liufuyang** [comment]
By the way, I was trying to speed up the build by increasing more memory, but I guess I am actually CPU bounded. The ecj compiling works much slower if I just use the usual javac compiler. Not sure if there is some good way can speed things up.

**Comment by TheMrMilchmann** [comment]
Hi @liufuyang, as you already found out, you can configure ECJ just like you would configure javac in Gradle.

> By the way, I was trying to speed up the build by increasing more memory, but I guess I am actually CPU bounded. The ecj compiling works much slower if I just use the usual javac compiler. Not sure if there is some good way can speed things up.

From my experience, the compilation speed heavily depends on the program. For example, ECJ is significantly better at compiling methods with many (dozens) overloads. In the past javac had some issues with generic bounds in some edge-cases, but since most of these are fixed now, I rarely use ECJ anymore.

**Comment by liufuyang** [comment]
Aha, that is nice to know. Thank you so much. And yes I suppose in our case it would be ideal if we could also use javac. However the project is large and many old code lines give errors when complied with javac. Perhaps one day we can fix all the places and make our code compiler agnostic :)
